# Generated by Django 5.0.2 on 2024-02-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20240228_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birth_Date',
            new_name='birthdate',
        ),
    ]
