# Generated by Django 5.0.2 on 2024-02-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_remove_book_rating_book_author_book_is_bestselling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
    ]
